### ISSUE TITLE
Possible to get the KafkaConsumer instance from KafkaReadStream ?

### ISSUE THREAD

**Issue by maxplanck76er** [vert-x3/vertx-kafka-client#10]
Hello,

I am using your kafka client and I wonder if it would be possible to access the org.apache.kafka.clients.consumer.KafkaConsumer instance directly in KafkaStream ?

I would like to use some methods like position(TopicPartition partition) not directly available using your KafkaStream wrapper.

Fine thank you.

**Comment by vietj** [comment]
yes it should be possible imho

**Comment by vietj** [comment]
just commited that : https://github.com/vert-x3/vertx-kafka-client/commit/b03fa9025043566adc7c8d8821412512eaab98b6

can you give a try ?

**Comment by maxplanck76er** [comment]
Great, Thank you so much !

**Comment by vietj** [comment]
btw if some ops are missing, you can contribute them to the vertx api to ease usage.

**Comment by ppatierno** [comment]
@vietj @maxplanck76er I don't like this way too much. If some methods are missing we should add it to the Kafka streams and Kafka polyglot wrapper avoiding to expose the internal Kafka client objects. Why do you think that it exposing them is the right solution ?

**Comment by vietj** [comment]
@ppatierno because Vert.x *should not get in the way* of the developer and if the developer really needs to access it then he will use magic reflection and set Accessible true to obtain it anyway.

**Comment by vietj** [comment]
that being said it should not preclude adding missing methods.

**Comment by maxplanck76er** [comment]
@ppatierno @vietj I have forked the repo and added the position method to KafkaStream.

The commit is [1fb878b](https://github.com/maxplanck76er/vertx-kafka-client/commit/1fb878b47df8444ae13863648e07aa8a0f09f484)

**Comment by vietj** [comment]
@maxplanck76er did you sign the Eclipse ECA ?

**Comment by maxplanck76er** [comment]
@vietj I didn't at the commit time but it's now done.

**Comment by vietj** [comment]
have you done a PR so we can review it ?

**Comment by maxplanck76er** [comment]
Sorry, done. 

https://github.com/vert-x3/vertx-kafka-client/pull/11
