### ISSUE TITLE
Scala excluded from kafka-client and added only in scope test

### ISSUE THREAD

**Issue by SHammade** [vert-x3/vertx-kafka-client#101]
Hi,

as I see with 3.5.1 scala is only included in the scope test:
https://github.com/vert-x3/vertx-kafka-client/commit/6bbcc117ac8036d005c552e180079b4d0413b3c4#diff-600376dffeb79835ede4a0b285078036
and because of the excluding from kafka_2.12 org.scala-lang.scala-library is missing as a dependency.

regards,
Serbest

**Comment by vietj** [comment]
@SHammade I think Scala is only used for utils in 1.0.0

**Comment by vietj** [comment]
I've run 3.5.1 with Kafka client and it works fine for me (but I haven't used the utils)

**Comment by SHammade** [comment]
Okay, I used the KafkaServerStartable for starting a lokal kafka to mock the remote server and its worked before without adding the dependencies.

**Comment by vietj** [comment]
Kafka has started to rewrite the client without Scala but some parts (the utils) still rely on it I think.
