### ISSUE TITLE
Add explicit poll method to the KafkaConsumer

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-kafka-client#105]
The current Vert.x Kafka client implementation is more stream oriented.
Using the underlying `KafkaReadStream` implementation, the related `KafkaConsumer` implementation just provides and handler to be registered in order for the upper level application getting messages after subscription. The internal implementation does the polling periodically.
I'd like to expose the poll in order to give users the possibility to drive the consumer behaviour so they can decide when to poll as it happens with native Kafka consumer.
I'm rising this issue in relation to a need for bridging HTTP to Kafka (using Vert.x Kafka client) where an incoming GET should be start a related poll and not having a pause/resume logic for that (using the current always polling approach).
@vietj is that reasonable for you? Maybe this poll should be exposed just by `KafkaConsumer` and not by `KafkaReaderStream` because it could "break" the streaming rule in some way?

**Comment by vietj** [comment]
is the poll blocking or is it an asynchronous poll, i.e `void poll(Handler<AsyncResult<Result>>)` ?

**Comment by ppatierno** [comment]
The native Kafka poll is blocking but of course for the KafkaConsumer in the Vert.x client I would expect a signature like you suggested. The internal behaviour should be quite similar to the private pollRecords method that we have in the KafkaReadStream.

**Comment by vietj** [comment]
that sounds a good option to me to provide a non stream version as well.

**Comment by ppatierno** [comment]
Closed by #106
