### ISSUE TITLE
Lost messages while consuming multiple partitions with one consumer

### ISSUE THREAD

**Issue by emasab** [vert-x3/vertx-kafka-client#112]
I'm experiencing lost messages while using a consumer subscribed to multiple partitions . The problem happens with batches of messages of more than 10 messages. 

What happens is that for some partitions only a multiple of 10 messages is received instead of receiving the complete batch for that one.

I've seen that putting a conditional breakpoint in class KafkaReadStreamImpl at this line 

```java
this.current = records.iterator();
```

with condition

```java
this.current.count()>0
```
causes the breakpoint to be triggered when the problem happens.

It seems that the iterator is overwritten while still full.

I've tried to fix it putting a limit of 1 to the number of polls active at a specific time and after this fix the problem never happens even after consuming hundreds of messages, while without the fix the problem happen often with less than one hundred messages.

My fix is in this pull request 

https://github.com/vert-x3/vertx-kafka-client/pull/111

Please let me know if you can reproduce the issue
Thanks

**Comment by ppatierno** [comment]
Is it feasible for you writing a test case which highlights the failure without your fix?

**Comment by emasab** [comment]
The issue happens with a single partition as well as multiple, when more batches are received one after one, but it usually happens when using a pause - commit - resume cycle.

**Comment by emasab** [comment]
solved by https://github.com/vert-x3/vertx-kafka-client/pull/113
