### ISSUE TITLE
Missing repository - not published yet?

### ISSUE THREAD

**Issue by mavencode01** [vert-x3/vertx-kafka-client#12]
I added this dependency to my pom files but unable to locate the dependency in the maven repository, where can I find this library? @vietj

**Comment by vietj** [comment]
@mavencode01 for now it is published in OSS sonatype SNAPSHOT  repository https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-kafka-client/

**Comment by mavencode01** [comment]
Cool, thanks!
