### ISSUE TITLE
Some RxJava classe are missing

### ISSUE THREAD

**Issue by elarbi** [vert-x3/vertx-kafka-client#13]
Hello,

I've cloned the repo and tried to launch the tests but the following classes are not present in the classpath : import io.vertx.rxjava.kafka.client.consumer.KafkaConsumer;
import io.vertx.rxjava.kafka.client.consumer.KafkaConsumerRecord;

(imports from the RxExamples.java)

Same problem in io.vertx.kafka.client.tests.RxConsumerTest 
"import io.vertx.rxjava.kafka.client.consumer.KafkaConsumer;" is not resolved.

**Comment by vietj** [comment]
they are generated in `ls target/generated-sources/annotations/io/vertx/rxjava/`, run `mvn compile first`

**Comment by elarbi** [comment]
Works pertty fine !
Thanks a lot
