### ISSUE TITLE
Port admin client to master

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-kafka-client#133]
Currently the new admin client is in 3.7 branch and not in master.

**Comment by ppatierno** [comment]
@vietj it sounds really strange. I added the new admin client alongside the old one on 3.7 marking it as deprecated. I added new client on master as well and removing the old one. I am quite sure about that. What happened?

**Comment by vietj** [comment]
I don't know either I haven't investigated but it seems it is not there right ?

**Comment by ppatierno** [comment]
It's here on master:

https://github.com/vert-x3/vertx-kafka-client/blob/master/src/main/java/io/vertx/kafka/admin/KafkaAdminClient.java

with the related implementation:

https://github.com/vert-x3/vertx-kafka-client/blob/master/src/main/java/io/vertx/kafka/admin/impl/KafkaAdminClientImpl.java

**Comment by vietj** [comment]
my bad my copy was not up to date and I thought I updated it sorry for the noise
