### ISSUE TITLE
allow .subscribe(Pattern ...) in KafkaConsumer

### ISSUE THREAD

**Issue by anthonyshull** [vert-x3/vertx-kafka-client#156]
Moved from vertx-rxjava. Allow the KafkaConsumer.subscribe(Pattern pattern) signature to be used in rxjava2.

**Comment by anthonyshull** [comment]
I believe this can be done just by changing @GenIgnore to @GenIgnore(GenIgnore.PERMITTED_TYPE)? Are there published contribution guidelines?

**Comment by ppatierno** [comment]
@vietj any thoughts?

**Comment by IRQs** [comment]
Is there a technical reason why this functionality has been disabled in the generation of the reactive Kafka client?

**Comment by okolawole-ebsco** [comment]
It appears that KafkaConsumer.subscribe(Pattern pattern) is not available in vertx-rx-java3  version 4.5.4. Is there a reason this change wouldn't expose the method during code gen?
