### ISSUE TITLE
Upgrade to Kafka 2.4.0

### ISSUE THREAD

**Issue by aesteve** [vert-x3/vertx-kafka-client#162]
Kafka 2.4.0 [has been released](https://www.apache.org/dist/kafka/2.4.0/RELEASE_NOTES.html) in december.

Not sure what the strategy of version alignment would be? Example of antagonist approaches:
* next major Vert.x upgrade (4.0.0) is used to also align with Kafka 2.4?
* publish two versions: `io.vertx:vertx-kafka_2.3:3.8.4` and  `io.vertx:vertx-kafka_2.4:3.8.4` like Scala does, for instance

Not sure how other (official) parts of the Vert.x stack tackle version alignment.

I can have a look at the required amount of work, but I'd like to know about the required version alignment strategy beforehand :) 

----- 

Note:
In some of my project I excluded `kafka-clients:2.3.0` from transitive dependencies and enforced `kafka-clients:2.4.0` as top-level dependency and it seems to be working (but I'm still very early in integration-test phase).

**Comment by ppatierno** [comment]
In general we always want to have latest Kafka version but before doing a simple pom file updated to the latest, you need to check that the entire Vert.x stack is not broken due to this update because it could need an updates in some other projects like the ZK cluster manager.
