### ISSUE TITLE
Uptake Apache Kafka client to latest version

### ISSUE THREAD

**Issue by jcguion** [vert-x3/vertx-kafka-client#196]
### Questions

We observed high CPU usage from an idle Kafka consumer and isolated the issue to a known problem that has been fixed in the Apache Kafka client ([KAFKA-10254](https://issues.apache.org/jira/browse/KAFKA-10254) & [KAFKA-10134](https://issues.apache.org/jira/browse/KAFKA-10134)) and made available as version 2.6.1 (current Vert.x Kafka dependency is on 2.6.0).

### Version

3.9.3, although current 3.9.6 SNAPSHOT has the same 2.6.0 dependency.

### Context

Consumer connects to Kafka broker and shows CPU burn.

### Suggestion

An uptake of the patched Apache Kafka client (2.6.1).

**Comment by vietj** [comment]
ping @ppatierno @cescoffier

**Comment by cescoffier** [comment]
It's the bug @tsegismont chased, and yes I confirm that the problem was fixed in the Apache Kafka client. Note that 2.7 is also available.

**Comment by sfitts** [comment]
Would be great to uptake at least 2.7 as it contains some features we'd love to leverage.  Any plans for that?

**Comment by vietj** [comment]
we actually have a planned upgrade to 3.0.0 when Vert.x 4.3.0 is released

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-kafka-client/pull/208
