### ISSUE TITLE
Update for Kafka Client 3.0

### ISSUE THREAD

**Issue by murphye** [vert-x3/vertx-kafka-client#207]
Of course, Apache Kafka 3 is here. It would be nice if Vert.x offered initial support here, maybe as experimental. Thanks!

Relevant links:
https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients/3.0.0
https://docs.confluent.io/3.0.0/upgrade.html#upgrade-client-applications
https://kafka.apache.org/0100/documentation.html#upgrade_10_breaking

**Comment by davsclaus** [comment]
yeah it can be removed, everybody uses the regular camel-kafka component
