### ISSUE TITLE
KafkaWriteStreamImpl.java uses a blocking function

### ISSUE THREAD

**Issue by poiuytrez** [vert-x3/vertx-kafka-client#21]
It is written in the official KafkaProducer documentation that 

> The send() method is asynchronous. When called it adds the record to a buffer of pending record sends and immediately returns. This allows the producer to batch together individual records for efficiency.
https://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

It is unfortunately not true. We can read on the description of the max.block.ms parameter: 
> The configuration controls how long KafkaProducer.send() and KafkaProducer.partitionsFor() will block.These methods can be blocked either because the buffer is full or metadata unavailable.Blocking in the user-supplied serializers or partitioner will not be counted against this timeout.
https://kafka.apache.org/documentation/

So if Kafka is down, the producer **send** method executed on the event loop (line 94 of KafkaWriteStreamImpl.java) will block the event loop thread:
```
// non blocking
this.producer.send(record, (metadata, err) -> {
```

**Comment by vietj** [comment]
so the javadoc is lying ?

**Comment by vietj** [comment]
is it possible to detect such case ? i.e if the producer is going to block or not ?

**Comment by poiuytrez** [comment]
The javadoc is lying. I don't think that we can detect it.

**Comment by vietj** [comment]
so now the only workaround is to use a worker verticle ?

**Comment by poiuytrez** [comment]
I think so...

**Comment by vietj** [comment]
do you know where this is blocking in the code ?

**Comment by poiuytrez** [comment]
This is an example:
[kafka-hackathon 2.zip](https://github.com/vert-x3/vertx-kafka-client/files/834678/kafka-hackathon.2.zip)

Just run the producer without any kafka running on your machine and it will hang.

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
so using an executeBlocking should be ok I think, I'll provide a patch for 3.4.1

**Comment by ppatierno** [comment]
@poiuytrez thanks for reporting this. It was on my todo list for the 3.4.1 release but you beat me on time. A long time ago I discussed about that on the Kafka mailing list because the get metadata action seems to be the cause of the problem when the producer can't connect to the Kafka server. We'll fix it using blocking code as @vietj said. :)
