### ISSUE TITLE
Offsets are committed out of order, which can lead to lost messages on failures/restarts

### ISSUE THREAD

**Issue by agapic** [vert-x3/vertx-kafka-client#219]
### Questions

Why does the Vertx Kafka client have 10 in-flight consumer handlers? Why isn't it configurable? https://github.com/vert-x3/vertx-kafka-client/blob/6a836011899fd5bdc705199785e510aae048e962/src/main/java/io/vertx/kafka/client/consumer/impl/KafkaReadStreamImpl.java#L238

### Version

Vertx 4.2.5, but bug exists in older versions too.

### Context

Messages are always read in order, but messages can be committed out of order. For example message N+1 can commit before N has even processed. If we crash, message N is gone.

Writing a simple test, we intentionally introduce a 2s delay every 5th message to see what happens with our Vertx Kafka Consumer. We introduce the delay by sleeping without blocking the event loop (vertx.executeBlocking(..))

*Reading messages* 375-400
INFO [vert.x-eventloop-thread-0] Consumer - Reading message 375
...
INFO [vert.x-eventloop-thread-0] Consumer - Reading message 400 

*Commit order (every 5th message is committed out of order - 381, 386, 391, etc)*
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 380
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 382
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 383
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 384
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 385
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 387
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 388
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 389
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 390
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 392
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 393
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 394
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 395
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 397
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 398
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 399
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 400
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 376
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 381
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 386
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 391
INFO [vert.x-eventloop-thread-0] Consumer - Committed offset 396

### Do you have a reproducer?

```
package chapter2.deploy;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Context;
import io.vertx.core.Handler;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import io.vertx.kafka.client.common.TopicPartition;
import io.vertx.kafka.client.consumer.KafkaConsumer;
import io.vertx.kafka.client.consumer.OffsetAndMetadata;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;

public class Consumer extends AbstractVerticle {

  private static final Logger logger = LoggerFactory.getLogger(Consumer.class);
  private static KafkaConsumer<byte[], byte[]> consumer = null;
  private static Vertx vertx;
  private final Map<String, String> kafkaConfig;
  private final Handler<ConsumerRecord<byte[], byte[]>> handler;

  public Consumer() {
    this.kafkaConfig = KafkaConfig.consumer("test-agapic");
    this.handler = Consumer::handle;
  }

  public static void handle(ConsumerRecord<byte[], byte[]> record) {
    logger.info("Reading message {} {}", record.offset());
    Promise p = Promise.promise();
    if (record.offset() % 5 == 0) {
      logger.info("Going to sleep");
      vertx.executeBlocking(promise -> {
        try {
          Thread.sleep(2000);
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
        p.complete();
      });
    } else {
      p.complete();
    }

    p.future().onComplete(res -> {
      long commitPosition = record.offset() + 1;
      TopicPartition tp = new TopicPartition("test-agapic", 0);
      OffsetAndMetadata om = new OffsetAndMetadata(commitPosition, "");
      Map<TopicPartition, OffsetAndMetadata> offsets = new HashMap<>();
      offsets.put(tp, om);
      consumer.commit(offsets, ex -> {
        logger.info("Committed offset {}", ex.result().get(tp).getOffset());
      });
    });
  }

  @Override
  public void init(Vertx vertx, Context context) {
    super.init(vertx, context);
    consumer = KafkaConsumer.create(vertx, this.kafkaConfig);
    Consumer.vertx = vertx;
  }

  @Override
  public void start(Promise<Void> promise) {
    logger.info("Start");

    consumer.subscribe("test-agapic",
      (result) -> {
        if (result.succeeded()) {
          consumer.handler(record -> {
            this.handler.handle(record.record());
          });
        } else {
          logger.error("Error consuming", result.cause());
        }
      });
  }

  @Override
  public void stop() {
    logger.info("Stop");
  }
}
```

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by vsabella** [comment]
False alarm, this is a bug in the sample code above in how it manages completion with futures and promises.

**Comment by agapic** [comment]
Closing this but how did the Vertx Kafka Client developers intend for the handler to be used? Is it meant to be synchronous? @vietj
