### ISSUE TITLE
Development issue: testCreatePartitionInTopicWithAssignment is flaky

### ISSUE THREAD

**Issue by jhughes24816** [vert-x3/vertx-kafka-client#228]
When I have worked on this repo I have found some tests to be flaky they are listed below. 
- AdminClientTest/testCreatePartitionInTopicWithAssignment
- ConsumerFailedCloseTest/testRebalance
- ConsumerTest/testRebalance

This issue to track work to fix these tests.

**Comment by jhughes24816** [comment]
@vietj please label as appropriate. Thanks, I intend to work on this in some of my downtime.

**Comment by aesteve** [comment]
#233 #235
