### ISSUE TITLE
endOffsets(Set<TopicPartition> topicPartitions) annotated with @GenIgnore

### ISSUE THREAD

**Issue by gkozyryatskyy** [vert-x3/vertx-kafka-client#237]
### Questions

According to this comment https://github.com/smallrye/smallrye-mutiny-vertx-bindings/issues/724#issuecomment-1491356428 `endOffsets(Set<TopicPartition> topicPartitions)` method is annotated with `@GenIgnore` so [smallrye-mutiny-vertx-bindings](https://github.com/smallrye/smallrye-mutiny-vertx-bindings) lib do not see this method during the generation. 

Here is the link to latest tag source https://github.com/vert-x3/vertx-kafka-client/blob/4.4.1/src/main/java/io/vertx/kafka/client/consumer/KafkaConsumer.java#L837

### Version

`vertx-kafka-client:4.3.7`

**Comment by tsegismont** [comment]
It is mandatory currently due to a limitation of Vert.x codegen

As a workaround, you can do this:

```java
Future<Map<TopicPartition, Long>> future = mutinyConsumer.getDelegate().endOffsets(topicPartitions);
Uni<Map<TopicPartition, Long>> uni = io.smallrye.mutiny.vertx.UniHelper.toUni(future);
```
