### ISSUE TITLE
Upgrade the apache kafka-client version to 3.4.0

### ISSUE THREAD

**Issue by AnshulAngaria** [vert-x3/vertx-kafka-client#246]
#### Describe the feature

Current latest vertx-kafka-client v4.4.1 uses apache kafka-client version 3.0.2
We need latest kafka-client version 3.4.0. Can we release this?

**Comment by tsegismont** [comment]
Is that possible @ppatierno ?

**Comment by AnshulAngaria** [comment]
@tsegismont I see this is already done https://github.com/vert-x3/vertx-kafka-client/pull/238. When is the due date for 4.4.2 release?

**Comment by tsegismont** [comment]
@AnshulAngaria #238 targets Vert.x 5, this has not been backported to 4.x (not sure it is feasible)

Thoughts @julianladisch ?

**Comment by AnshulAngaria** [comment]
@julianladisch Yes I have manually updated the kafka-client, that has fixed my issue.

**Comment by AnshulAngaria** [comment]
@julianladisch Will manually upgrading kafka-client might introduce some breaking changes ?

**Comment by ppatierno** [comment]
I don't see problems to upgrade to kafka 3.4.0 even for a Vert.x 4.4.x patch release. But I see that the discussion moved forward and now it's targeted for Vert.x 5.

**Comment by tsegismont** [comment]
Thank you @ppatierno
