### ISSUE TITLE
Using Serdes Kafka class as factory for serializer/deserializer

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-kafka-client#4]
See PR #3

**Comment by matzew** [comment]
Once there is a Debezium release that supports `0.10.1.1` or later, we can do this.

also, related: https://github.com/vert-x3/vertx-kafka-client/issues/5

**Comment by matzew** [comment]
I am happy to help here on this too ;-)

**Comment by ppatierno** [comment]
I'm going to close on behalf of #20
