### ISSUE TITLE
Updating to 0.10.1.1 Kafka client

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-kafka-client#6]
After updating pom.xml with new version, adding new following methods : 

- endOffsets

**Comment by doernemt** [comment]
Are there any plans yet to upgrade to .1.1 ? 
We'd be very interested, because we need the new API to resolve an offset by timestamp (`public Map<TopicPartition, OffsetAndTimestamp> offsetsForTimes(Map<TopicPartition, Long> timestampsToSearch)` in KafkaConsumer

Happy to help with a PR.
