### ISSUE TITLE
Using vertx-kafka-client can break logging

### ISSUE THREAD

**Issue by sirgantrithon** [vert-x3/vertx-kafka-client#62]
After including the vertx-kafka-client jar (and its dependencies) into my fatjar, my application logging broke.  I am using the vert.x slf4j delegate factory and logback as the logging implementation.

After looking at the dependencies for the vertx-kafka-client, I excluded log4j and the slf4j-log4j bridge that vertx-kafka-client has declared dependencies on and my logging worked again.

I was wondering if something could be done with the dependency management of this project to mitigate this, and if that isn't easy or acceptable, could it be mentioned in the docs?

Thanks!

**Comment by vietj** [comment]
I think this is due to the `io.vertx.kafka.admin` addition that brought the `org.apache.kafka:kafka_2.12` dependency that brings log4j.

Perhaps should should handle differently this dependency and mark it as _optional_ or move `io.vetx.kafka.admin` in another maven module.

@cescoffier WDYT ?

**Comment by cescoffier** [comment]
SLF4J dependencies on bridges should be marked as optional or excluded. SLF4J API version needs to be aligned with the vert.x core one.

Whether or not the admin needs to be in another module, I don't know. Would that make sense?

**Comment by vietj** [comment]
the admin tools have an hard dependency on log4j and slf4jlog4j bridge

**Comment by vietj** [comment]
that being said, someone can use the client without the admin tools and thus not required log4j/slf4jlog4j

**Comment by ppatierno** [comment]
regarding the admin features, the Kafka team added them in one of the latest release and inside their "clients" module. The objective was having the user application able to not just consume/produce messages for Kafka but even create topic, changing configuration on them and so on. To me it makes sense to leave the admin as part of the client in all one module having the same behaviour as Kafka.

**Comment by ppatierno** [comment]
@vietj do you think can we close this one?

**Comment by vietj** [comment]
I think yes
