### ISSUE TITLE
Support passing Serializer / Deserializer instances when building producer/consumer/stream

### ISSUE THREAD

**Issue by AGutan** [vert-x3/vertx-kafka-client#64]
I would like to use my own deserializer.

Something like this:

```
import org.apache.kafka.common.serialization.Deserializer;
import java.util.Map;

public class MyDeserializer<T> implements Deserializer<T> {

  Class<T> classType;
  CustomDeserializer custDes;

  public MyDeserializer(Class<T> classType) {
    this.classType = classType;
    
   custDes = new CustDes.config();
   custDes.preregisterSomeClassesForPerformance(Class1.class,Class2.class);
  }

  @Override
  public void configure(Map<String, ?> map, boolean b) { }

  @Override
  public T deserialize(String s, byte[] bytes) {

    Object deserializedObject = custDes.deserialize(bytes);
    return classType.cast(deserializedObject);

  }

  @Override
  public void close() {}
}
```
 

Any advice on using the KafkaConsumer and directly deserialize the bytes from Kafka with my Deserializer.

I tried deserializing with BufferDeserializer first then with MyDeserializer wich works. But I would like to know if there's a way to do it without the intermediate BufferDeserializer. 

*Assuming data has been originally serialized with my custom serializer.

**Comment by AGutan** [comment]
For example modern stream processing engines have KafkaConsumer constructor like this:

`KafkaConsumer<String, MyClass1>new KafkaConsumer(... , new CustomDeserializer<>(MyClass1.class) , ...);`

which is kind of the way I would prefer

**Comment by vietj** [comment]
how about providing a Kafka `Serde<T>` ?

**Comment by vietj** [comment]
actually just providing serializer/deserizalizer seems trivial to add, I will come up with a PR

**Comment by AGutan** [comment]
@vietj Thx for the tip. Got it. But would be nice to have direct parameters for ser/deserializers. Otherwise I would have to operate on the KafkaReadStream and provide a ser/des.

**Comment by vietj** [comment]
@AGutan I've made a PR that add support for direct passing of Serializer / Deserializer, would you mind to check if that is what you need ?

**Comment by AGutan** [comment]
@vietj Yep. Thx a lot!
