### ISSUE TITLE
commit with a simple handler does not get callback

### ISSUE THREAD

**Issue by plenderyou** [vert-x3/vertx-kafka-client#68]
KafkaConsumerImpl
  @Override
  public void commit(Handler<AsyncResult<Void>> completionHandler) {
    this.stream.commit(completionHandler != null ? ar -> ar.map((Object) null) : null);
  }

The above commit line never calls the completion handler passed in. 
Should this not be
  @Override
  public void commit(Handler<AsyncResult<Map<TopicPartition, OffsetAndMetadata>>> completionHandler) {
    this.commit(null, completionHandler);
  }

**Comment by vietj** [comment]
can you provide a reproducer for this issue ?

**Comment by vietj** [comment]
the thing is that `Handler<AsyncResult<Map<TopicPartition, OffsetAndMetadata>>>` is not polyglot, so if you need this feature you should use the the underlying stream with `consumer.asStream()`

**Comment by plenderyou** [comment]
I'm not sure what you mean by 'it's not polyglot' 
  /**
   * Commit current offsets for all the subscribed list of topics and partition.
   *
   * @param completionHandler handler called on operation completed
   */

The documentation says that after the commit call is made, the callback gets called. At the moment it doesn't

Using the underlying stream is a workaround I believe but it's still a bug either in the docs or the implementation

**Comment by plenderyou** [comment]
Also the signature in the original was wrong.

 @Override
  public void commit(Handler<AsyncResult<Void>> completionHandler) {
    this.stream.commit(completionHandler != null ? ar -> ar.map((Object) null) : null);
  }

the completion handler's handle method is never called

**Comment by vietj** [comment]
oh right!

**Comment by vietj** [comment]
so obvious I didn't see it
