### ISSUE TITLE
Does consumer has timeout?

### ISSUE THREAD

**Issue by datafibers** [vert-x3/vertx-kafka-client#69]
How can I set timeout for consumer pulling (or poll) the records. Or timeout the consumer.handler

**Comment by vietj** [comment]
I think you should user a Vertx timer and if the timer has fired before the result, go on and discard the result

**Comment by vietj** [comment]
also poll is event driven so that would not make much sense and I think the best is that you use timers as your you case seems specific, if you are timing out a consumer it means you are expecting data from the stream

**Comment by doernemt** [comment]
I agree with @datafibers . The other effect of having a fixed poll timeout is that the performance of vertx KafkaConsumer is not as good as it could be. Consider the case that you start the consumer (via setting a handler) and after that you want to seek to a different position, pause, ... whatever. If the consumer does not receive data, the poll() operation will block the whole second until the ExecutorService will execute the next command.
Having the timeout configurable, we'd give users of our client the freedom to choose how often the ExecutorService will be able to do other things than waiting for the consumer to timeout.

@vietj : If you agree, I will prepare a PR.

**Comment by vietj** [comment]
@doernemt good point, but it seems to be a different concern to me, @datafibers seems to need an application timeout, not related to internal reasons. go ahead with the PR
