### ISSUE TITLE
Empty KafkaConsumer.exceptionHandler

### ISSUE THREAD

**Issue by kbt** [vert-x3/vertx-kafka-client#70]
According to doc, KafkaConsumer.exceptionHandler() should set an exception handler
http://vertx.io/docs/vertx-kafka-client/java/#_handling_errors
http://vertx.io/docs/apidocs/io/vertx/rxjava/kafka/client/consumer/KafkaConsumer.html#exceptionHandler-io.vertx.core.Handler-

But what it does is simply return _this_ instance
https://github.com/vert-x3/vertx-kafka-client/blob/e4b15db9003e060fdf8d20b4e694260c4a21a8b9/src/main/java/io/vertx/kafka/client/consumer/impl/KafkaReadStreamImpl.java#L495

**Comment by ppatierno** [comment]
It's fixed by 47b7b3dbc43f3e8bf7adb7da01cd088b6da424bc
