### ISSUE TITLE
seek operations might return wrong offset after a previous poll

### ISSUE THREAD

**Issue by doernemt** [vert-x3/vertx-kafka-client#71]
We noticed that, e.g., seekToBeginning might return a too-high offset if the client has been polling before.
Imagine something like this:
```
// Create a topic with 500 records and then 
    TopicPartition topicPartition = new TopicPartition(topic, 0);
    consumer.assign(Collections.singleton(topicPartition), assignRes -> {
      // Start polling...
      consumer.handler(record -> {
        // Nothing to do
      });
      // Seek to offset 0
      consumer.seekToBeginning(Collections.singleton(topicPartition), res -> {
        consumer.position(topicPartition, ctx.asyncAssertSuccess(posRes -> {
          ctx.assertEquals(0L, posRes, "Expecting offset 0 after seek to 0");
          done.complete();
        }));
      });
    });
```
You would assume that seekToBeginning returns the offset 0, instead it will return a much higher value, because the consumer did start polling when consumer.handler was called. Then, seek does run (and indeed finds the correct offset), but because ```current``` is not null, ```run()``` will continue to run and increment the offset ...

A PR with a fix will follow shortly.

**Comment by vietj** [comment]
fixed by PR
