### ISSUE TITLE
Using new Admin Client API

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-kafka-client#77]
Using the new Admin Client API (starting from 0.11.0 version) implemented in Java instead of the old AdminUtils Scala used in the current status.

**Comment by datafibers** [comment]
+1 up. The current AdminUtils is still  using zookeeper. Expect to see update to latest kafka admin client

**Comment by vietj** [comment]
that would be so awesome to remove kafka, however we need to check the various upgraded versions such as Zookeeper, etc....

**Comment by doernemt** [comment]
I will look into it. Cannot promise a date, but I'll do my best. May be before 3.5.1 release, let's see.

**Comment by ppatierno** [comment]
@doernemt no worries. I'm going to start to work on it. Thanks ;)
