### ISSUE TITLE
Client swallowing polling exceptions

### ISSUE THREAD

**Issue by hekonsek** [vert-x3/vertx-kafka-client#78]
Hi @ppatierno,

I've found a small issue with `pollRecords` method (https://github.com/vert-x3/vertx-kafka-client/blob/master/src/main/java/io/vertx/kafka/client/consumer/impl/KafkaReadStreamImpl.java#L134). So right now if there is an exception during poll (for example here - https://github.com/vert-x3/vertx-kafka-client/blob/master/src/main/java/io/vertx/kafka/client/consumer/impl/KafkaReadStreamImpl.java#L138), the exception will not be reported not propagated to the client. That means for example that if you forgot set set `group.id` property on consumer, messages will not be consumed by client, but you will see now Kafka client error. Basically without debugger you cannot nail any polling exception.

I'm wondering how can we improve this? Maybe we could propagate errors from worker thread to exception handler?

**Comment by vietj** [comment]
yes we should do that, can you provide a test in the existings tests and someone will contribute the fix :-)

**Comment by vietj** [comment]
I'm scheduling it for 3.5.1

**Comment by ppatierno** [comment]
@hekonsek added on my to-do list but providing a test could be really useful as @vietj suggested ;)

**Comment by hekonsek** [comment]
I've created pull request #79 with a fix and test covering the scenario I was referring to. 

BTW It seems that `KafkaReadStreamImpl#exceptionHandler` invocation was ignoring handler passed as an argument. I fixed that as well.

So with my fix in place all exceptions generated during polling process will be nicely handled by `exceptionHandler{}`.

**Comment by hekonsek** [comment]
Just one thing came to my mind - should we check if exception handler is null before calling it? I guess that it is optional, so it can be null.

**Comment by hekonsek** [comment]
Yeah, we should do it. Added NPE check against exception handler.

**Comment by hekonsek** [comment]
Many thanks for review and merging, Paolo.
