### ISSUE TITLE
Documentation urls are broken

### ISSUE THREAD

**Issue by elarbi** [vert-x3/vertx-kafka-client#8]
Hello,

In the documentation page : https://github.com/vert-x3/vertx-kafka-client/blob/initial-work/src/main/asciidoc/java/index.adoc
the references to javadoc are broken e.g. https://github.com/vert-x3/vertx-kafka-client/blob/initial-work/src/main/apidocs/io/vertx/kafka/client/consumer/KafkaConsumer.html

Regards

**Comment by vietj** [comment]
Hi,

you cannot have them right now, they will be available when published on the website.

or you can  get them from this archive in the meantime : https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-kafka-client/3.4.0-SNAPSHOT/vertx-kafka-client-3.4.0-20170213.114652-63-docs.zip
