### ISSUE TITLE
Add subscription via topics pattern 

### ISSUE THREAD

**Issue by MrGarry2016** [vert-x3/vertx-kafka-client#88]
when I use vertx Kafka consumer, I want to provide a Kafka topic pattern and the consumer can consume each topic that matches this pattern. This is useful when a new topic is created, it can be found automatically and consumed. Does vertx right now support this?

**Comment by marco-admyre** [comment]
As consumer.consume(Pattern... is part of the Kafka client lib it should really be exposed to the Vertx side too.

**Comment by anhldbk** [comment]
@MrGarry2016 I'm afraid not. Vertx implementation is just a layer on top of Apache Kafka Consumer which does NOT support consume messages by topic patterns

**Comment by marco-admyre** [comment]
This is part of the consumer so would it not be possible to use it
```

public void subscribe​(java.util.regex.Pattern pattern,
                      ConsumerRebalanceListener listener)
```

Taken from:

(https://kafka.apache.org/20/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html)

**Comment by anhldbk** [comment]
@marco-admyre Sorry for my outdated knowledge about Kafka Consumers.

It's a good idea to make a PR against this issue!

**Comment by ye32007** [comment]
Has the problem been solved ？

**Comment by ppatierno** [comment]
@ye32007 @anhldbk @marco-admyre there is PR #132 to address this one now.
