### ISSUE TITLE
Mouse pointing issue in documentation

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-kafka-client#94]
When i'm pointing my mouse on a code snippet [here](http://vertx.io/docs/vertx-kafka-client/scala/), a language name appear at the beginning of the snippet.

In this case my mouse is not pointing on the code snippet, so it's fine:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/16746106/37342255-1296268c-26d5-11e8-9cc4-294c68264446.png">

In this case my pointer is on the code snippet:
![image](https://user-images.githubusercontent.com/16746106/37342467-b825fc4e-26d5-11e8-88d9-e0daa7701292.png)

So, what `javascript` at the begging of the snippet mean?

I'm using Firefox browser 58.0.2, but the issue also appear in the Google Chrome browser

**Comment by Sammers21** [comment]
@vietj, is it seems to be a vertx-docgen issue?

**Comment by vietj** [comment]
yes, we need to figure out where this happens (i.e is it in adoc files or when processing the site ?)

**Comment by ppatierno** [comment]
I noticed this problem in all the code snippets on the Vert.x web site. Maybe we could close this one because it's not strictly related to this component.
