### ISSUE TITLE
Typed configuration for consumer

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-kafka-client#95]
Currently in order to consumer messages from Kafka you need to provide a class name for key and value deserialization.

I don't think that it is convenient, compiler will not help you to observe the error until you will run your application. I would propose to add a way for providing a consumer configuration for key and value  deserialization by providing instances of such deserializers.

**Comment by Sammers21** [comment]
I also thinking that the Producer API should have the same ability

**Comment by ppatierno** [comment]
This is the way how the native Kafka client configuration work. Even if we allow to pass instant here, we won't use them but just get the fully qualified class name for passing it to the native Kafka client. For this reason I don't think that this makes sense.

**Comment by Sammers21** [comment]
@ppatierno, agree

**Comment by vietj** [comment]
agreed also, we should keep kafka usage as close to the real kafka as possible
