### ISSUE TITLE
Create a KafkaProducerRecord with headers

### ISSUE THREAD

**Issue by bnjdpn** [vert-x3/vertx-kafka-client#99]
Since Kafka 0.11.0.0, it's now possible to add headers to a record.
See : https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers#KIP-82-AddRecordHeaders-Status

Is it possible to create KafkaProducerRecord with headers ?

Thanks.

**Comment by tsegismont** [comment]
@ppatierno can you please take a look? Thanks

**Comment by ppatierno** [comment]
The feature was added.
